# Використовуємо офіційний Python образ як базовий
FROM python:3.9-slim

# Встановлюємо робочу директорію в контейнері
WORKDIR /app

# Копіюємо requirements.txt і встановлюємо залежності
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо весь код додатку
COPY . .

# Відкриваємо порт для веб-додатку
EXPOSE 5000

# Запускаємо Flask додаток
CMD ["python", "app/app.py"]
